### ISSUE TITLE
Authenticated!  Not enough data to parse

### ISSUE THREAD

**Issue by i3laze** [samuelthomas2774/airport#2]
```
# acp features -h 192.168.10.137 -p passhere

Authenticating
getA: client key length 191 is less than the recommended 256 bits
Authenticated!
Error: Not enough data to parse
    at Function.parse (C:\Users\user\AppData\Roaming\npm\node_modules\node-acp\dist\lib\cflbinary.js:185:19)
    at Function.parse (C:\Users\user\AppData\Roaming\npm\node_modules\node-acp\dist\lib\cflbinary.js:27:37)
    at Client.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\node-acp\dist\lib\client.js:260:44)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user\AppData\Roaming\npm\node_modules\node-acp\dist\lib\client.js:5:58)
```

I'm actually trying to change a country code on Airport Extreme 802.11ac.. running latest f/w 7.9.1

**Comment by init4** [comment]
I think latest firmware the protocol is different. I can't even enable SSH on 7.9.1.

**Comment by i3laze** [comment]
Just in case..
Seems here’s the latest manual how to fix the AirPort country code:
https://sites.google.com/site/lapastenague/a-deconstruction-of-routers-and-modems/apple-time-capsule-repair/change-country-on-airport-router

Never tried, cause I’m already on Xiaomi AX3600.
